-- 5. add_course: 
--  This routine is used to add a new course. 
--  inputs: course title, course description, course area, and duration(in terms of hours).
--  The course identifier is generated by the system.
create procedure add_course(title text, course_description text, course_area_name text, duration integer)
    language plpgsql
as
$$
DECLARE
    id INT;
BEGIN
    SELECT MAX(course_id) + 1 INTO id FROM Courses;
    INSERT INTO Courses (course_id,course_area_name,title,course_description,duration)
    VALUES (id,course_area_name,title,course_description,duration);
END;
$$;


